import { prisma } from "./db";
import { getSettingNumber } from "./settings";
import { fmtCoins } from "./wallet";
import { notifyReferralCommission } from "./telegram";

// ────────────────────────────────────────────────────────────────────────────
// Referral revenue share (casino commission).
//
// A referrer earns a configurable % (default 25) of the HOUSE FEE on every
// SETTLED bet placed by a user they referred — never from the bet amount,
// winnings, deposits or withdrawals. One ReferralCommission per bet (unique
// betId). Created PENDING by the hourly job scanning settled bets, released to
// AVAILABLE after the lock period, then CLAIMED through the SAME referral
// balance as the welcome bonus (no separate referral wallet).
//
// Settlement happens in the separate engine service, so commissions are
// generated by scanning already-settled bets (status WON/LOST/CASHED) rather
// than hooking settlement directly — a scalable, decoupled integration.
// ────────────────────────────────────────────────────────────────────────────

const DAY_MS = 24 * 60 * 60 * 1000;
const SETTLED = ["WON", "LOST", "CASHED"];
// Only scan recently-settled bets — rounds settle within minutes of placement,
// so a few days' lookback (with the unique-betId dedup) captures everything
// without scanning the full bet history each run.
const LOOKBACK_DAYS = 4;

export async function getRevenueShareConfig(): Promise<{ pct: number; lockDays: number }> {
  const [pct, lockDays] = await Promise.all([
    getSettingNumber("referral_revenue_share_pct"),
    getSettingNumber("referral_commission_lock_days"),
  ]);
  return { pct: pct > 0 ? pct : 25, lockDays: lockDays > 0 ? lockDays : 7 };
}

/**
 * Create PENDING commissions for newly-settled referred bets that don't have one
 * yet. Idempotent — the unique betId prevents duplicates even under concurrency.
 */
export async function generateReferralCommissions(): Promise<number> {
  const { pct, lockDays } = await getRevenueShareConfig();
  if (pct <= 0) return 0;

  const since = new Date(Date.now() - LOOKBACK_DAYS * DAY_MS);
  const bets = await prisma.bet.findMany({
    where: { status: { in: SETTLED }, feeAmount: { gt: 0 }, createdAt: { gte: since } },
    orderBy: { createdAt: "desc" },
    take: 5000,
    select: { id: true, userId: true, feeAmount: true, createdAt: true },
  });
  if (!bets.length) return 0;

  // Drop bets that already have a commission.
  const existing = new Set(
    (
      await prisma.referralCommission.findMany({
        where: { betId: { in: bets.map((b) => b.id) } },
        select: { betId: true },
      })
    ).map((r) => r.betId)
  );
  const fresh = bets.filter((b) => !existing.has(b.id));
  if (!fresh.length) return 0;

  // Resolve referrers (only referred users earn their referrer a commission).
  const userIds = [...new Set(fresh.map((b) => b.userId))];
  const referrers = new Map(
    (
      await prisma.user.findMany({
        where: { id: { in: userIds }, referredBy: { not: null } },
        select: { id: true, referredBy: true },
      })
    ).map((u) => [u.id, u.referredBy as string])
  );

  let created = 0;
  for (const b of fresh) {
    const owner = referrers.get(b.userId);
    if (!owner || owner === b.userId) continue;
    const commissionAmount = Math.round((b.feeAmount * pct) / 100);
    if (commissionAmount <= 0) continue;
    try {
      await prisma.referralCommission.create({
        data: {
          ownerUserId: owner,
          referredUserId: b.userId,
          betId: b.id,
          houseFee: b.feeAmount,
          commissionPercent: pct,
          commissionAmount,
          status: "PENDING",
          availableAt: new Date(b.createdAt.getTime() + lockDays * DAY_MS),
        },
      });
      created++;
    } catch (e) {
      // P2002 (unique betId) = created concurrently — fine.
      const code = (e as { code?: string })?.code;
      if (code !== "P2002") console.error("[referral-commission] create failed:", e);
    }
  }
  return created;
}

/**
 * Move PENDING → AVAILABLE for commissions whose lock has elapsed, then notify
 * each owner of the total released. Safe under concurrency (status re-checked in
 * the updateMany).
 */
export async function releaseReferralCommissions(): Promise<number> {
  const now = new Date();
  const due = await prisma.referralCommission.findMany({
    where: { status: "PENDING", availableAt: { lte: now } },
    take: 10_000,
  });
  if (!due.length) return 0;

  const { count } = await prisma.referralCommission.updateMany({
    where: { id: { in: due.map((d) => d.id) }, status: "PENDING" },
    data: { status: "AVAILABLE", releasedAt: now },
  });

  // Notify each owner of the total that just became available (batched).
  const byOwner = new Map<string, number>();
  for (const d of due) byOwner.set(d.ownerUserId, (byOwner.get(d.ownerUserId) ?? 0) + d.commissionAmount);
  const owners = await prisma.user.findMany({
    where: { id: { in: [...byOwner.keys()] } },
    select: { id: true, username: true },
  });
  const nameOf = new Map(owners.map((u) => [u.id, u.username]));
  for (const [owner, total] of byOwner) {
    await notifyReferralCommission({ username: nameOf.get(owner) ?? "—", uid: owner, coins: fmtCoins(total) });
  }
  return count;
}

/** One cycle: generate new commissions, then release matured ones. */
export async function processReferralCommissions(): Promise<{ generated: number; released: number }> {
  const generated = await generateReferralCommissions();
  const released = await releaseReferralCommissions();
  return { generated, released };
}

// ── Admin referral-revenue overview ──────────────────────────────────────────

/** Aggregate stats + top referrers for the admin Referral Revenue section. */
export async function getReferralRevenueOverview(days = 30) {
  const startOfToday = new Date();
  startOfToday.setHours(0, 0, 0, 0);
  const since = new Date(Date.now() - days * DAY_MS);

  const [pending, available, claimed, all, releasedToday, topGroups] = await Promise.all([
    prisma.referralCommission.aggregate({ _sum: { commissionAmount: true }, _count: { _all: true }, where: { status: "PENDING" } }),
    prisma.referralCommission.aggregate({ _sum: { commissionAmount: true }, _count: { _all: true }, where: { status: "AVAILABLE" } }),
    prisma.referralCommission.aggregate({ _sum: { commissionAmount: true }, _count: { _all: true }, where: { status: "CLAIMED" } }),
    prisma.referralCommission.aggregate({ _sum: { commissionAmount: true, houseFee: true }, _count: { _all: true } }),
    prisma.referralCommission.aggregate({ _sum: { commissionAmount: true }, _count: { _all: true }, where: { releasedAt: { gte: startOfToday } } }),
    prisma.referralCommission.groupBy({
      by: ["ownerUserId"],
      _sum: { commissionAmount: true },
      _count: { _all: true },
      where: { createdAt: { gte: since } },
      orderBy: { _sum: { commissionAmount: "desc" } },
      take: 20,
    }),
  ]);

  const owners = await prisma.user.findMany({
    where: { id: { in: topGroups.map((g) => g.ownerUserId) } },
    select: { id: true, username: true },
  });
  const nameOf = new Map(owners.map((u) => [u.id, u.username]));

  return {
    pending: pending._sum.commissionAmount ?? 0,
    pendingCount: pending._count._all,
    available: available._sum.commissionAmount ?? 0,
    availableCount: available._count._all,
    claimed: claimed._sum.commissionAmount ?? 0,
    totalPaid: (available._sum.commissionAmount ?? 0) + (claimed._sum.commissionAmount ?? 0),
    totalCommissions: all._sum.commissionAmount ?? 0,
    totalHouseFee: all._sum.houseFee ?? 0,
    totalCount: all._count._all,
    releasedToday: releasedToday._sum.commissionAmount ?? 0,
    releasedTodayCount: releasedToday._count._all,
    topReferrers: topGroups.map((g) => ({
      userId: g.ownerUserId,
      username: nameOf.get(g.ownerUserId) ?? "—",
      total: g._sum.commissionAmount ?? 0,
      bets: g._count._all,
    })),
  };
}
